# The database, and the credentials nobody ever types.
#
# The manifest asked for `engine: postgres, size: small`. Everything below is
# the platform team's opinion about what that should mean, applied identically
# every time. Encryption, isolated placement, backup windows and secret
# handling are not decisions a developer is asked to make.

resource "aws_db_subnet_group" "this" {
  count = local.has_database ? 1 : 0

  name        = "${local.prefix}-db"
  description = "Isolated tier for ${var.name}"
  subnet_ids  = data.aws_subnets.isolated.ids

  tags = merge(local.tags, { Name = "${local.prefix}-db" })
}

resource "random_password" "db" {
  count = local.has_database ? 1 : 0

  length  = 32
  special = false
}

resource "aws_db_instance" "this" {
  count = local.has_database ? 1 : 0

  identifier     = "${local.prefix}-db"
  engine         = local.dbe.engine
  engine_version = local.dbe.engine_version
  instance_class = local.db.instance_class
  port           = local.dbe.port

  allocated_storage     = local.db.allocated_storage
  max_allocated_storage = local.db.allocated_storage * 4
  storage_type          = "gp3"
  storage_encrypted     = true

  db_name  = replace(var.name, "-", "_")
  username = "app"
  password = random_password.db[0].result

  db_subnet_group_name   = aws_db_subnet_group.this[0].name
  vpc_security_group_ids = [aws_security_group.db[0].id]

  # Not configurable, and not exposed in the schema. An isolated subnet with no
  # internet route makes this redundant, which is the point: two independent
  # controls, neither relying on the other being correct.
  publicly_accessible = false

  backup_retention_period = local.db_retention_days
  backup_window           = "03:00-04:00"
  maintenance_window      = "Mon:04:00-Mon:05:00"
  multi_az                = var.database.multi_az
  copy_tags_to_snapshot   = true

  auto_minor_version_upgrade = true
  deletion_protection        = local.is_prod
  skip_final_snapshot        = !local.is_prod
  final_snapshot_identifier  = local.is_prod ? "${local.prefix}-final-${formatdate("YYYYMMDDhhmmss", timestamp())}" : null

  performance_insights_enabled = true
  enabled_cloudwatch_logs_exports = [
    var.database.engine == "postgres" ? "postgresql" : "error"
  ]

  tags = merge(local.tags, { Name = "${local.prefix}-db" })

  lifecycle {
    ignore_changes = [final_snapshot_identifier]
  }
}

# ---------------------------------------------------------------------------
# credentials
#
# Generated here, written to Secrets Manager, and read by the task at runtime.
# They are never in the manifest, never in a plaintext environment variable and
# never in the repository. The task role can read this secret and nothing else.
# ---------------------------------------------------------------------------

resource "aws_secretsmanager_secret" "db" {
  count = local.has_database ? 1 : 0

  name        = "/${var.environment}/${var.name}/db"
  description = "Database credentials for ${var.name}, generated by the platform"

  recovery_window_in_days = local.is_prod ? 30 : 0

  tags = local.tags
}

resource "aws_secretsmanager_secret_version" "db" {
  count = local.has_database ? 1 : 0

  secret_id = aws_secretsmanager_secret.db[0].id

  secret_string = jsonencode({
    engine   = local.dbe.engine
    host     = aws_db_instance.this[0].address
    port     = local.dbe.port
    dbname   = aws_db_instance.this[0].db_name
    username = aws_db_instance.this[0].username
    password = random_password.db[0].result
  })
}
