# The root configuration the pipeline applies.
#
# It is deliberately almost empty. All the opinion lives in the module, and all
# the intent lives in the manifest. This file only connects the two, which is
# why nobody ever needs to edit it and why the agent is never asked to.
#
#   terraform plan -var-file=dev-checkout.tfvars.json
#
# The tfvars file is generated by platform/bin/render.py and is never written
# by hand.

terraform {
  required_version = ">= 1.9"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.80"
    }

    awscc = {
      source  = "hashicorp/awscc"
      version = ">= 1.0"
    }

    random = {
      source  = "hashicorp/random"
      version = ">= 3.6"
    }
  }

  # Backend is supplied by the pipeline with -backend-config, so the same root
  # config serves every environment without a copy per environment.
  #
  # use_lockfile is S3-native locking, so there is no separate DynamoDB lock
  # table to create or pay for.
  backend "s3" {
    use_lockfile = true
  }
}

provider "aws" {
  default_tags {
    tags = {
      ManagedBy = "platform"
    }
  }
}

provider "awscc" {}

module "service" {
  source = "../platform/modules/service"

  name          = var.name
  environment   = var.environment
  owner         = var.owner
  cost_centre   = var.cost_centre
  manifest_path = var.manifest_path

  runtime       = var.runtime
  ingress       = var.ingress
  database      = var.database
  permissions   = var.permissions
  observability = var.observability
}
